### ISSUE TITLE
Registracia + prihlasenie

### ISSUE THREAD

**Issue by LubicaDubravcova** [LubicaDubravcova/WEBTE2_zav_zadanie#1]
Aplikáciu budú mocť používať len zaregistrovaní užívatelia. Využite pritom vlastnú registráciu, kde loginom bude emailová adresa, ktorú použijete neskôr aj na komunikáciu v rámci aplikácie. Zaregistrovať sa bude dať dvojakým spôsobom:

-  každý jednotlivec vyplnením registračného formuláru, keď mu príde potvrdzovací mail, na základe ktorého dokáže dokončiť registráciu.

-  Administrátor dokáže zaregistrovať viacerých ľudí hromadne po importe csv súboru, ktorého vzor nájdete v prílohe tohoto zadania. Takto importovaným užívateľom bude prednastavené defaultné heslo, ktoré si budú musieť pri prvom prihlásení do systému zmeniť.
Aplikácia podporuje 3 roly – užívateľ, administrátor a anonymný neprihlásený hosť stránky.

**Comment by Rikpat** [comment]
Registrácia a prihlásenie hotová, ešte spravím administrátorské účty a jeho interface na pridávanie

**Comment by dasmitha** [comment]
Pri registrácii mi píše, že sa heslá nezhodujú aj keď sa určite zhodujú (paste-ol som do oboch kolóniek)

**Comment by Rikpat** [comment]
ja tento problem nemam, nejde ti to teda odoslat?

**Comment by NicollRose** [comment]
Taktiež mi pri registrácii píše, že sa heslá nezhodujú (nekopírovala som ich).

**Comment by minop** [comment]
Mne zase píše, že sa už používa moj e-mail

**Comment by Rikpat** [comment]
Pretoze sa pridal do tabulky jeden stlpec a phpcko este nikto neupravil...

**Comment by Rikpat** [comment]
hotove
