### ISSUE TITLE
Titulna stranka dostupna bez prihlasenia

### ISSUE THREAD

**Issue by LubicaDubravcova** [LubicaDubravcova/WEBTE2_zav_zadanie#10]
Na titulnej stránke celej aplikácie (dostupnej bez prihlásenia) zobrazte mapu Slovenska, kde vyznačíte podľa toho, čo si vyberie anonymný hosť stránky,

- buď odkiaľ pochádzajú jednotliví zaregistrovaní užívatelia

- alebo kde navštevujú svoju školu. V prípade, že jednu školu navštevuje viacero užívateľov, musí to byť z mapy jednoznačne jasné.
Tieto údaje dostanete do aplikácie na základe údajov z csv súborov importovaných na základe úlohy #1.

**Comment by Rikpat** [comment]
Done
